### ISSUE TITLE
pslg_datastructure.reverse_surface_orinetation missing

### ISSUE THREAD

**Issue by YarUnderoaker** [Samson-Mano/Constrained_Delaunay_Triangulation#1]
Hi.
In map_generator.cs method detect_surfaces used  pslg_datastructure.reverse_surface_orinetation which not implemented in pslg_datastructure.

**Comment by Samson-Mano** [comment]
Updated pslg_datastructure.cs with method reverse_surface_orientation added in class surface_store. Also removed the usage of this method. Need to look into this method if it has any usage.

The code works fine without reverse_surface_orientation being used.

**Comment by YarUnderoaker** [comment]
Accepted. Thanks for your work.
